/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import controller.FabricanteController;
import helper.Conexao;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Fabricante;

/**
 *
 * @author Luciano
 */
public class telaFabricantePesquisa extends javax.swing.JFrame {

    public void mostrarTabela(){
        
        EntityManager em = Conexao.getInstancia().getMysqlPU();

            List<Fabricante> fabricantes = em.createQuery("select c from Fabricante c ", Fabricante.class).getResultList();

            DefaultTableModel model = (DefaultTableModel) tabelaFabricante.getModel();
            model.setNumRows(0);

            for (Fabricante fabricante : fabricantes) {

                Object[] linhasLista = {
                    fabricante.getCodigo(),
                    fabricante.getNome()};
                model.addRow(linhasLista);
                tabelaFabricante.setModel(model);

            }
    
    }
    
    /**
     * Creates new form telaFabricantePesquisa
     */
    public telaFabricantePesquisa() {
        initComponents();
        mostrarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFabricante = new javax.swing.JTable();
        botaoNovoFabricante = new javax.swing.JButton();
        botaoRemoverFabricante = new javax.swing.JButton();
        caixaRemoverFabricante = new javax.swing.JTextField();
        labelRemover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaFabricante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaFabricante);

        botaoNovoFabricante.setText("Novo");
        botaoNovoFabricante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoNovoFabricanteMouseClicked(evt);
            }
        });

        botaoRemoverFabricante.setText("Remover");
        botaoRemoverFabricante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoRemoverFabricanteMouseClicked(evt);
            }
        });

        labelRemover.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        labelRemover.setText("Digite o Codigo para Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRemover)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(caixaRemoverFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoRemoverFabricante)))
                        .addGap(266, 266, 266))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(botaoNovoFabricante)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(botaoNovoFabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(labelRemover)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRemoverFabricante)
                    .addComponent(caixaRemoverFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovoFabricanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoNovoFabricanteMouseClicked
        new telaFabricante().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoNovoFabricanteMouseClicked

    private void botaoRemoverFabricanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRemoverFabricanteMouseClicked
        
        try{
        Fabricante fabricante = new Fabricante(Long.parseLong(caixaRemoverFabricante.getText()));
        FabricanteController fcontroller = new FabricanteController(fabricante);
        if(fcontroller.removerFabricante()){
            mostrarTabela();
        }
        
        }catch(NumberFormatException e1){JOptionPane.showMessageDialog(null, "Codigo Incorreto!");}
    }//GEN-LAST:event_botaoRemoverFabricanteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaFabricantePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaFabricantePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaFabricantePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaFabricantePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaFabricantePesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoNovoFabricante;
    private javax.swing.JButton botaoRemoverFabricante;
    private javax.swing.JTextField caixaRemoverFabricante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelRemover;
    private javax.swing.JTable tabelaFabricante;
    // End of variables declaration//GEN-END:variables
}
