/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import controller.FabricanteController;
import helper.Conexao;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Fabricante;

public class TelaFabricantePesquisa extends javax.swing.JFrame {

    private List<Fabricante> temporario = new ArrayList<>();

    public void mostrarTabela() {

        EntityManager em = Conexao.getInstancia().getMysqlPU();

        List<Fabricante> fabricantes = em.createQuery("select c from Fabricante c ", Fabricante.class).getResultList();

        DefaultTableModel model = (DefaultTableModel) tabelaFabricante.getModel();
        model.setNumRows(0);

        for (Fabricante fabricante : fabricantes) {

            Object[] linhasLista = {
                fabricante.getCodigo(),
                fabricante.getNome()};
            model.addRow(linhasLista);
            tabelaFabricante.setModel(model);

        }

    }

    /**
     * Creates new form telaFabricantePesquisa
     */
    public TelaFabricantePesquisa() {
        initComponents();
        mostrarTabela();
        botaoEditarFabricante.setVisible(false);
        caixaNomeFabricante.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFabricante = new javax.swing.JTable();
        botaoNovoFabricante = new javax.swing.JButton();
        botaoRemoverFabricante = new javax.swing.JButton();
        caixaRemoverFabricante = new javax.swing.JTextField();
        labelRemover = new javax.swing.JLabel();
        botaoEditarFabricante = new javax.swing.JButton();
        caixaCodigoFabricante = new javax.swing.JTextField();
        botaoBuscarFabricante = new javax.swing.JButton();
        caixaNomeFabricante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaFabricante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaFabricante);

        botaoNovoFabricante.setText("Novo");
        botaoNovoFabricante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoNovoFabricanteMouseClicked(evt);
            }
        });

        botaoRemoverFabricante.setText("Remover");
        botaoRemoverFabricante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoRemoverFabricanteMouseClicked(evt);
            }
        });

        labelRemover.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        labelRemover.setText("Digite o Codigo para Remover");

        botaoEditarFabricante.setText("Editar");
        botaoEditarFabricante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEditarFabricanteMouseClicked(evt);
            }
        });

        botaoBuscarFabricante.setText("Buscar");
        botaoBuscarFabricante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoBuscarFabricanteMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Editar Fabricante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(botaoNovoFabricante)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(caixaRemoverFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRemoverFabricante))
                    .addComponent(labelRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(caixaCodigoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoBuscarFabricante)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(caixaNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEditarFabricante))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)))
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(botaoNovoFabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelRemover)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoRemoverFabricante)
                            .addComponent(caixaRemoverFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaCodigoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoBuscarFabricante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caixaNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoEditarFabricante))))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovoFabricanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoNovoFabricanteMouseClicked
        new TelaFabricante().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoNovoFabricanteMouseClicked

    private void botaoRemoverFabricanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRemoverFabricanteMouseClicked

        try {
            Fabricante fabricante = new Fabricante(Long.parseLong(caixaRemoverFabricante.getText()));
            FabricanteController fcontroller = new FabricanteController(fabricante);
            if (fcontroller.removerFabricante()) {
                mostrarTabela();
            }

        } catch (NumberFormatException e1) {
            JOptionPane.showMessageDialog(null, "Codigo Incorreto!");
        }
    }//GEN-LAST:event_botaoRemoverFabricanteMouseClicked

    private void botaoEditarFabricanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarFabricanteMouseClicked

        try{
        Fabricante fabricante = new Fabricante(Long.parseLong(caixaCodigoFabricante.getText()));
        FabricanteController fabricantecontroller = new FabricanteController(fabricante);
        
        if(caixaNomeFabricante.equals("")){JOptionPane.showMessageDialog(null, "Nome Vazio!");}
        else{fabricantecontroller.EditarFabricante();
        
        }
        mostrarTabela();
        }catch(NumberFormatException e1){JOptionPane.showMessageDialog(null, "Digite o Codigo do Fabricante!");}
    }//GEN-LAST:event_botaoEditarFabricanteMouseClicked

    private void botaoBuscarFabricanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBuscarFabricanteMouseClicked
        
        try{
        Fabricante fabricante = new Fabricante(Long.parseLong(caixaCodigoFabricante.getText()));
        
        FabricanteController fabricantecontroller = new FabricanteController(fabricante);
        
        fabricantecontroller.buscarFabricante();
        botaoEditarFabricante.setVisible(true);
        caixaNomeFabricante.setVisible(true);
       
        }catch(NumberFormatException e1){JOptionPane.showMessageDialog(null, "Digite o Codigo do Fabricante!");}
        
    }//GEN-LAST:event_botaoBuscarFabricanteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFabricantePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFabricantePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFabricantePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFabricantePesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFabricantePesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscarFabricante;
    private javax.swing.JButton botaoEditarFabricante;
    private javax.swing.JButton botaoNovoFabricante;
    private javax.swing.JButton botaoRemoverFabricante;
    public static javax.swing.JTextField caixaCodigoFabricante;
    public static javax.swing.JTextField caixaNomeFabricante;
    private javax.swing.JTextField caixaRemoverFabricante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelRemover;
    private javax.swing.JTable tabelaFabricante;
    // End of variables declaration//GEN-END:variables
}
